const fs = require('fs');
const path = require('path');

const deployment = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'deployment.json'), 'utf8'));
const artifact = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'artifacts', 'contracts', 'CardGame.sol', 'CardGame.json'), 'utf8'));

const content = `// Auto-generated by scripts/exportToFrontend.js
export const CONTRACT_ADDRESS = "${deployment.address}";

export const CONTRACT_ABI = ${JSON.stringify(artifact.abi, null, 2)};
`;

const destPath = path.join(__dirname, '..', 'frontend', 'src', 'constants.js');
fs.writeFileSync(destPath, content);

console.log(`✅ Frontend constants exported to ${destPath}`);
